const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const context = { exports: {} };
vm.runInNewContext(ts.transpileModule(fs.readFileSync('shared/ai-work.ts', 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText, context);
const { extractBlocks, validateProposal, buildRequests, inverseEdits } = context.exports;
const doc = { tabs: [{ documentTab: { body: { content: [{startIndex:1,paragraph:{elements:[{startIndex:1,textRun:{content:'Hello world\n'}}]}},{startIndex:13,paragraph:{elements:[{startIndex:13,textRun:{content:'image'}},{inlineObjectElement:{}}]}},{table:{tableRows:[{tableCells:[{content:[{startIndex:30,paragraph:{elements:[{startIndex:30,textRun:{content:'Second\n'}}]}}]}]}]}}]}},tabProperties:{tabId:'t1'}}] };
const blocks = extractBlocks(doc);
assert.equal(blocks.length,2); assert.equal(blocks[0].text,'Hello world'); assert.equal(blocks[1].startIndex,30);
const edits = validateProposal({summary:'Fix',edits:[{blockId:blocks[0].id,after:'Hello Earth'},{blockId:blocks[1].id,after:'Third'}]},blocks).edits;
assert.equal(edits.length,2);
assert.throws(()=>validateProposal({summary:'',edits:[{blockId:'unknown',after:'bad'}]},blocks));
assert.throws(()=>validateProposal({summary:'',edits:[edits[0],edits[0]]},blocks));
assert.throws(()=>validateProposal({summary:'',edits:[{blockId:blocks[0].id,after:'Hello world'}]},blocks));
const reqs=buildRequests(blocks,edits);
assert.equal(reqs[0].deleteContentRange.range.startIndex,30); assert.equal(reqs[0].deleteContentRange.range.tabId,'t1');
assert.equal(reqs.find(req=>req.deleteContentRange?.range.startIndex===7).deleteContentRange.range.startIndex,7); assert.equal(reqs.find(req=>req.insertText?.text==='Earth').insertText.text,'Earth');
const inverse=inverseEdits(blocks,edits);
assert.equal(inverse.edits[0].after,'Hello world'); assert.equal(inverse.blocks[1].startIndex,30);
const emoji=[{id:'emoji',tabId:'t1',startIndex:1,text:'a😀b'}];
const emojiReqs=buildRequests(emoji,[{blockId:'emoji',after:'a😃b'}]);
assert.equal(emojiReqs[0].deleteContentRange.range.startIndex,2); assert.equal(emojiReqs[0].deleteContentRange.range.endIndex,4);
console.log('AI Work patch safety OK');
const styled=[{id:'styled',startIndex:1,text:'bad BOLD bad',styles:[{offset:0,length:4,style:{}},{offset:4,length:4,style:{bold:true}},{offset:8,length:4,style:{}}]}];
assert.throws(()=>buildRequests(styled,[{blockId:'styled',after:'good BOLD good'}]),/định dạng/);
assert.equal(buildRequests(styled,[{blockId:'styled',after:'bad BOLD good'}]).length,3);
const bold=[{id:'bold',startIndex:1,text:'see OLD now',styles:[{offset:0,length:4,style:{}},{offset:4,length:3,style:{bold:true}},{offset:7,length:4,style:{}}]}];
assert.equal(buildRequests(bold,[{blockId:'bold',after:'see NEW now'}])[2].updateTextStyle.textStyle.bold,true);

