import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
const implementation = await import('./phone-history.ts').catch(() => null);
assert.ok(implementation, 'admin history reader must exist');
assert.ok(process.env.FIRESTORE_EMULATOR_HOST, 'history tests must use emulator');
const app = initializeApp({ projectId: 'demo-phone-confirmation' }, 'history-test');
const db = getFirestore(app);
const targetUid = `history-${Date.now()}`;
await db.collection('users').doc(targetUid).set({ confirmedPhoneNumber: '+84335784563', phoneNumber: '+84335784563' });
await db.collection('users').doc(targetUid).collection('phoneConfirmations').doc('one').set({ phoneNumber: '+84335784563', confirmedAt: '2026-10-01T00:00:00Z', method: 'email_otp' });
await db.collection('users').doc(`duplicate-${targetUid}`).set({ phoneNumber: '0335784563' });
const { readPhoneHistory } = implementation;
await assert.rejects(readPhoneHistory(db, 'member', 'member@example.com', targetUid), /quản trị/i);
const result = await readPhoneHistory(db, 'owner', 'giathieu110406@gmail.com', targetUid);
assert.equal(result.events.length, 1);
assert.equal(result.events[0].phoneNumber, '+84335784563');
assert.equal(result.duplicatePhone, true);
await assert.rejects(readPhoneHistory(db, 'owner', 'giathieu110406@gmail.com', '../users'), /hợp lệ/i);
await deleteApp(app);
console.log('admin phone history tests passed');
