import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
const implementation = await import('./phone-confirmation-store.ts').catch(() => null);
assert.ok(implementation, 'transactional phone confirmation store must exist');
assert.ok(process.env.FIRESTORE_EMULATOR_HOST, 'integration tests require Firestore emulator; never production');
const app = initializeApp({ projectId: 'demo-phone-confirmation' }, 'phone-store-tests');
const db = getFirestore(app);
const { createPhoneConfirmationStore } = implementation;
const store = createPhoneConfirmationStore(db);
const now = new Date('2026-10-01T00:00:00Z');
const uid = `store-${Date.now()}`;
const email = 'fixture@example.com';
const user = db.collection('users').doc(uid);
await user.set({ phoneNumber: '', planType: 'trial', planExpiresAt: 12345 });
const reserve = (id: string, time = now, phone = '+84912345689') => store.reserveSend(uid, phone, email, id, 'hash', time);
const results = await Promise.allSettled([reserve('one'), reserve('two')]);
assert.equal(results.filter(result => result.status === 'fulfilled').length, 1, 'concurrent sends respect cooldown');
const record = (await db.collection('email_verifications').doc(uid).get()).data()!;
const challengeId = record.challengeId;
await assert.rejects(store.verify(uid, email, 'hash', now), /gửi|email/i, 'cannot consume unsent OTP');
await store.markDelivered(uid, challengeId);
await assert.rejects(store.verify(uid, 'changed@example.com', 'hash', now), /email/i);
const verified = await Promise.allSettled([store.verify(uid, email, 'hash', now), store.verify(uid, email, 'hash', now)]);
assert.equal(verified.filter(result => result.status === 'fulfilled').length, 1, 'only one transaction consumes the challenge');
const profile = (await user.get()).data()!;
assert.equal(profile.confirmedPhoneNumber, '+84912345689');
assert.equal(profile.phoneConfirmationVersion, 1);
assert.equal(profile.planType, 'trial');
assert.equal(profile.planExpiresAt, 12345);
assert.equal((await user.collection('phoneConfirmations').get()).size, 1);
await assert.rejects(reserve('change', new Date(now.getTime() + 60000), '+84335784563'), /khóa/i);
for (let index = 1; index < 5; index++) await reserve(`hour-${index}`, new Date(now.getTime() + index * 60000));
await assert.rejects(reserve('limit-hour', new Date(now.getTime() + 5 * 60000)), /giờ/i);
for (let index = 0; index < 5; index++) await reserve(`day-${index}`, new Date(now.getTime() + 3600000 + index * 60000));
await assert.rejects(reserve('limit-day', new Date(now.getTime() + 7200000)), /24/i);
const later = new Date(now.getTime() + 86400000);
await reserve('rollover', later);
await store.markDelivered(uid, 'rollover');
for (let index = 0; index < 5; index++) await assert.rejects(store.verify(uid, email, 'wrong', later), /mã|lần/i);
await assert.rejects(store.verify(uid, email, 'hash', later), /lần/i);
const expiry = new Date(later.getTime() + 3600000);
await reserve('expiry', expiry);
await store.markDelivered(uid, 'expiry');
await assert.rejects(store.verify(uid, email, 'hash', new Date(expiry.getTime() + 600000)), /hết hạn/i);
assert.equal((await user.collection('phoneConfirmations').get()).size, 1, 'failed attempts do not create history');
assert.equal((await db.collection('email_verifications').doc(uid).get()).data()?.sendTimes.length, 6, 'expiry does not reset send limits; four sends from hour one remain within the rolling day');
await deleteApp(app);
console.log('phone confirmation store integration tests passed');
